opam-version: "2.0"
synopsis: "Effects-based OCaml Nameserver"
description: "Effects-based OCaml Nameserver"
maintainer: ["Ryan Gibb"]
authors: ["Ryan Gibb"]
license: "MIT"
homepage: "https://github.com/RyanGibb/eon"
doc: "https://url/to/documentation"
bug-reports: "https://github.com/RyanGibb/eon/issues"
depends: [
  "ocaml" {>= "5.0.0"}
  "dune" {>= "3.4"}
  "eio_main" {>= "1.0"}
  "dns"
  "dns-server"
  "dns-resolver"
  "dns-tsig"
  "cmdliner" {>= "1.1.0" & < "2.0.0"}
  "fmt"
  # tun
  "tuntap"
  # acme
  "letsencrypt" {= "dev"}
  "letsencrypt-dns" {= "dev"}
  "cohttp-eio" {>= "6.0.0"}
  "mirage-crypto-rng-eio"
  # cap
  "capnp-rpc-unix" {>= "2.0"}
  # hibernia
  "wol" {= "dev"}
  "wol-eio" {= "dev"}
]
build: [
  [
    "dune"
    "build"
    "-p"
    name
    "-j"
    jobs
    "@install"
    "@runtest" {with-test}
    "@doc" {with-doc}
  ]
]
dev-repo: "git+https://github.com/RyanGibb/eon.git"
